import Head from "next/head";
import Image from "next/image";
import { Container, Typography } from "@mui/material";
import { useAuthContext } from "@/firebase/auth";

export default function Home() {
  const { user }: any = useAuthContext();

  return (
    <>
      <Head>
        <title>Psychopal</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container className="align-center">
        <Typography variant="h1" sx={{ mt: 20 }}></Typography>
        <Typography variant="h4">A modern web application template</Typography>
        <Typography variant="h4">Welcome {user?.email}</Typography>
      </Container>
    </>
  );
}
